spring:
  application:
    name: clothing_store

  logging:
    level:
      org.springframework: DEBUG
      com.java6.asm.clothing_store: DEBUG

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/clothingstore}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:admin123}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      url: ${REDIS_URL}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER:default} # Thêm username từ biến REDISUSER
      password: ${REDIS_PASSWORD} # Thêm password từ biến REDISPASSWORD
      timeout: ${REDIS_TIMEOUT:6000}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:10}
          max-idle: ${REDIS_POOL_MAX_IDLE:5}
          min-idle: ${REDIS_POOL_MIN_IDLE:2}
          max-wait: ${REDIS_POOL_MAX_WAIT:2000}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/auth/google/success}

admin:
  email: ${ADMIN_EMAIL:admin@gmail.com}
  password: ${ADMIN_PASSWORD:admin123}

# Cấu hình CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN_1:http://localhost:5173}

# Cấu hình bổ sung để tăng bảo mật
server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:false}
        http-only: true
  port: ${SERVER_PORT:8080}