spring:
  application:
    name: clothing_store

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      org.springframework.data.redis: DEBUG
      org.springframework.jdbc: DEBUG

  datasource:
    url: jdbc:mysql://localhost:3306/clothingstore
    username: root
    password: admin123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 2000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 48118088678-cbdk6ns2d8a8bba01enlc4ja6fmdgs4f.apps.googleusercontent.com
            client-secret: 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
  #            redirect-uri: http://localhost:8080/oauth2/authorization/google
  #            redirect-uri: "http://localhost:8080/auth/google/success"

  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_EMAIL}